package com.example.projectdraft

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/*Read explanation at the complete bottom to understand how SQL Database is used in Android Studio*/
/*This file contains the product table*/

@Entity(
    /*@Entity – tells Room that this Kotlin data class is a table. */
    foreignKeys = [
        ForeignKey(
            entity = CategoriesEntity::class,
            parentColumns = ["id"], //The column from the categories entity
            childColumns = ["categoryId"],//The column in the products entity that needs the id
            onDelete = ForeignKey.CASCADE //So that if a category is deleted, the rows that use it here also get deleted
        )
    ]
)
data class ProductEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    /*@PrimaryKey(autoGenerate = true) – marks id as the unique identifier for each row.
     The autoGenerate flag makes Room fill this value for you when you insert a new row.
     The reason we have assigned it to 0 is because Room requires us to do this for autogenerate.
     Everytime you insert data and it needs to autogenerate, it looks for a default placeholder
     which is 0 in this case (but it could also be set to null), then it replaces that placeholder
     with the actual value it has autogenerated*/
    /*Below we have the columns of the table*/
    val name: String,
    val categoryId: Int, //You've already specified above that this is a foreign key
    val price: Double,
    val imageRes: Int // optional – if you're using drawable images
)

//This is not an entity. It is just a data class that holds the result of joining the products and category names
data class ProductWithName(
    val id: Int,
    val name: String,
    val price: Double,
    val categoryId: Int,//This won't be used but I just wanted it included
    @ColumnInfo(name = "catName")
    val categoryName: String,
    val imageRes: Int
)

/*Ok so for Android studio, the connection is done a differently if you are using SQL. You use sth called
 Room which is a google library that lets you work with your database using plain Kotlin or Java instead of
 raw SQL. Room gives you 3 main pieces:
* An Entity = What data looks like
* A DAO = How to get/store the data
* A Database = Where the data lives
* Example for the Product table I've used the following files:
* ProductEntity.kt for the Entity
* ProductDao.kt for the DAO
* App Database that will be used for all tables.
*/